language: dart
sudo: false
dart:
  - stable
  - dev
env:
  - TEST_PLATFORM=vm
cache:
  directories:
    - $HOME/.pub-cache
matrix:
  fast_finish: true
  allow_failures:
    - dart: dev
script:
  - set -e && pub run test:test
