name: specify
version: 1.1.0
authors:
  - George D. Cooksey, III <texdc3@gmail.com>
description: Simple, yet powerful and flexible specifications
homepage: https://github.com/texdc/specify-dart
environment:
  sdk: '>=1.15.0 <2.0.0'
dev_dependencies:
  test: '^0.12.7'
